# Generated by Django 2.2.16 on 2022-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220704_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Post comment', 'verbose_name_plural': 'Post comments'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Subscribe', 'verbose_name_plural': 'Subscribes'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group of post', 'verbose_name_plural': 'Groups of post'},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribe'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='posts_follow',
        ),
    ]
