# Generated by Django 2.2.16 on 2022-07-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220707_2113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
